import React, { createContext, useContext, useState, useEffect } from 'react';

export type Lang = 'hu' | 'en';

const STORAGE_KEY = 'nd_lang';

type LanguageContextType = {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string, ...args: (string | number)[]) => string;
};

const translations: Record<Lang, Record<string, string>> = {
  hu: {
    site_name: 'NovaDrive Motors',
    nav_inventory: 'Aktuális kínálat',
    nav_about: 'Rólunk',
    nav_faq: 'GYIK',
    nav_contact: 'Kapcsolat',
    nav_admin: 'Admin belépés',
    nav_admin_dashboard: 'Admin felület',
    footer: 'NovaDrive Motors · Demo autókereskedés · Minden tartalom csak bemutató célokat szolgál.',
    topbar_phone: 'Telefon: +36 20 123 4567',
    topbar_email: 'E-mail: info@novadrive.hu',
    logo_subtitle: 'Premium Car Studio · Demo',
    meta_description: 'NovaDrive demo autókereskedés – modern, letisztult autó katalógus aktuális készlettel, részletes adatlapokkal, galériával és online kapcsolatfelvétellel.',
    meta_og_desc: 'Letisztult, ügyfélvonzó autó katalógus demo oldal kereskedéseknek.',

    hero_title: 'Autóink – prémium készletről',
    hero_lead: '{{n}} db gépjárművel várjuk látogatóinkat. Böngéssz kínálatunkban, szűrj típus, kategória vagy ár szerint, és vedd fel velünk a kapcsolatot egy kattintással.',
    hero_cta: 'Megnézem a katalógust',
    hero_banner: 'Készletről {{n}} db gépjármű',

    inventory_title: 'Most érkezett',
    inventory_subtitle: 'Böngéssz típus, kategória vagy ár szerint – a találati listát valós időben szűrheted és rendezheted.',
    inventory_count: '{{n}} db',
    inventory_loading: 'Kínálat betöltése...',
    inventory_error: 'Nem sikerült betölteni a kínálatot. Kérjük, frissítsd az oldalt később.',
    inventory_empty: 'Nincs a szűrésnek megfelelő autó. Módosítsd a keresési feltételeket, vagy töröld a szűrőket.',
    inventory_aria: 'Elérhető autók listája',

    filter_title: 'Kereső',
    filter_make: 'Márka',
    filter_make_all: 'Összes márka',
    filter_category: 'Kategória',
    filter_category_all: 'Összes',
    filter_sort: 'Rendezés',
    filter_sort_default: 'Alapértelmezett',
    filter_sort_price_asc: 'Ár szerint növekvő',
    filter_sort_price_desc: 'Ár szerint csökkenő',
    filter_sort_date_desc: 'Legújabb elöl',
    filter_sort_date_asc: 'Legrégebbi elöl',
    filter_price_min: 'Ár (tól) Ft',
    filter_price_max: 'Ár (ig) Ft',
    filter_color: 'Szín',
    filter_color_all: 'Összes szín',
    filter_power_min: 'Teljesítmény (min) LE',
    filter_power_max: 'Teljesítmény (max) LE',
    filter_search: 'Keresés',
    filter_search_count: 'Keresés ({{n}} db)',
    filter_clear: 'Keresési feltételek törlése',

    car_sold: 'Eladva',
    car_featured: 'A kínálatunk',
    car_details: 'Részletek megtekintése',
    car_back: 'Vissza a katalógushoz',
    car_year: 'Gyártási év',
    car_mileage: 'Futott kilométer',
    car_fuel: 'Üzemanyag',
    car_transmission: 'Váltó',
    car_body: 'Karosszéria',
    car_category: 'Kategória',
    car_offer: 'Kérd egyedi ajánlatunkat vagy foglalj tesztvezetést.',
    car_loading: 'Autó adatlap betöltése...',
    car_error: 'Nem található az autó vagy hiba történt a betöltés közben.',
    car_not_found: 'Az autó nem található.',
    car_gallery_aria: 'Autó képgaléria',
    car_table_aria: 'Autó adatlap',
    car_image_alt: '{{0}} - {{1}}. kép',

    contact_title: 'Kapcsolat',
    contact_subtitle: 'Írj nekünk néhány kattintással – ha szeretnéd, válaszd ki azt az autót is, amelyik felkeltette az érdeklődésed.',
    contact_name: 'Név',
    contact_email: 'E-mail cím',
    contact_phone: 'Telefonszám (opcionális)',
    contact_car: 'Érintett autó (opcionális)',
    contact_car_none: 'Nincs konkrét autó',
    contact_car_helper: 'Válaszd ki, melyik autóval kapcsolatban írsz, így gyorsabban tudunk segíteni.',
    contact_message: 'Üzenet',
    contact_submit: 'Üzenet elküldése',
    contact_sending: 'Küldés folyamatban...',
    contact_error_required: 'Kérjük, töltsd ki a nevet, e-mail címet és az üzenetet.',
    contact_success: 'Köszönjük a megkeresést! Hamarosan felvesszük veled a kapcsolatot.',
    contact_error_send: 'Hiba történt az üzenet elküldése közben. Kérjük, próbáld meg később újra.',
    contact_hours_title: 'Nyitvatartás',
    contact_hours_weekday: 'Hétfő–Péntek: 9:00–18:00',
    contact_hours_saturday: 'Szombat: 9:00–14:00',
    contact_hours_sunday: 'Vasárnap: Zárva',
    contact_social_title: 'Kövess minket',
    contact_address_title: 'Cím',
    contact_address: '1234 Budapest, Autó utca 1.',

    about_title: 'Rólunk',
    about_meta_title: 'Rólunk | NovaDrive Motors',
    about_intro: 'A NovaDrive Motors több mint egy autókereskedés – egy olyan közösség, ahol a minőség, az őszinteség és az ügyfélközpontúság minden lépésnél az első helyen áll.',
    about_mission_title: 'Küldetésünk',
    about_mission: 'Prémium és megbízható gépjárműveket kínálunk ügyfeleinknek, átlátható feltételekkel és személyre szabott szolgáltatással. Minden autónkat alaposan átvizsgáljuk, hogy biztos lehess benne: amit kapsz, azt is kapod.',
    about_values_title: 'Értékeink',
    about_value_quality_title: 'Minőség',
    about_value_quality: 'Csak gondosan válogatott, ellenőrzött járműveket kínálunk.',
    about_value_transparency_title: 'Átláthatóság',
    about_value_transparency: 'Nincs rejtett költség – az ár az ár, minden egy helyen látható.',
    about_value_service_title: 'Szolgáltatás',
    about_value_service: 'Személyre szabott tanácsadás, finanszírozási lehetőségek és csereautó-becslés.',
    about_cta: 'Nézd meg kínálatunkat vagy vedd fel velünk a kapcsolatot.',

    admin_login_title: 'Admin belépés',
    admin_login_subtitle: 'Zárt felület a kereskedés számára. A demóhoz használd az',
    admin_login_subtitle2: 'adatpárt.',
    admin_email: 'E-mail',
    admin_password: 'Jelszó',
    admin_demo: 'Demo: admin@example.com / admin',
    admin_submit: 'Belépés',
    admin_submitting: 'Beléptetés...',
    admin_error_connection: 'Nem sikerült a kapcsolódás. Indítsd el a backendet: cd backend && uvicorn app.main:app --port 8000',
    admin_error_credentials: 'Hibás belépési adatok. Használd: admin@example.com / admin',

    admin_dash_title: 'Admin felület',
    admin_dash_subtitle: 'Kezeld az eladásra kínált autókat és a kapcsolatfelvételi üzeneteket egy helyen.',
    admin_logout: 'Kijelentkezés',

    admin_cars_title: 'Készletkezelés',
    admin_cars_count: '{{n}} autó a rendszerben',
    admin_cars_add: 'Új autó felvétele',
    admin_cars_loading: 'Autók betöltése...',
    admin_cars_error: 'Nem sikerült betölteni az autókat.',
    admin_cars_col_car: 'Autó',
    admin_cars_col_price: 'Ár (HUF)',
    admin_cars_col_category: 'Kategória',
    admin_cars_col_status: 'Státusz',
    admin_cars_col_actions: 'Műveletek',
    admin_cars_edit: 'Szerkesztés',
    admin_cars_sold: 'Eladottként',
    admin_cars_reactivate: 'Vissza aktívba',
    admin_cars_delete: 'Törlés',
    admin_cars_status_sold: 'Eladva',
    admin_cars_status_active: 'Aktív',
    admin_cars_modal_edit: 'Autó adatainak szerkesztése',
    admin_cars_modal_add: 'Új autó felvétele',
    admin_cars_label_title: 'Titel',
    admin_cars_label_make: 'Márka',
    admin_cars_label_model: 'Modell',
    admin_cars_label_year: 'Év',
    admin_cars_label_mileage: 'Futott km',
    admin_cars_label_fuel: 'Üzemanyag',
    admin_cars_label_transmission: 'Váltó',
    admin_cars_label_body: 'Karosszéria',
    admin_cars_label_category: 'Kategória',
    admin_cars_label_images: 'Képek feltöltése',
    admin_cars_upload_text: 'Kattints vagy húzd ide a képeket (több fájl kiválasztható)',
    admin_cars_uploading: 'Feltöltés folyamatban...',
    admin_cars_main_image: 'Fő kép',
    admin_cars_label_urls: 'Vagy képek URL-jei (vesszővel elválasztva)',
    admin_cars_label_description: 'Leírás',
    admin_cars_label_extras: 'Extrák (vesszővel elválasztva)',
    admin_cars_cancel: 'Mégse',
    admin_cars_save: 'Mentés',
    admin_cars_saving: 'Mentés...',
    admin_cars_confirm_delete: 'Biztosan törlöd:',

    admin_messages_title: 'Beérkezett üzenetek',
    admin_messages_count: '{{n}} üzenet összesen',
    admin_messages_loading: 'Üzenetek betöltése...',
    admin_messages_error: 'Nem sikerült betölteni az üzeneteket.',
    admin_messages_col_sender: 'Feladó',
    admin_messages_col_message: 'Üzenet',
    admin_messages_col_car: 'Kapcsolódó autó',
    admin_messages_col_status: 'Státusz',
    admin_messages_col_action: 'Művelet',
    admin_messages_mark_handled: 'Jelölés kezeltként',
    admin_messages_status_new: 'Új',
    admin_messages_status_handled: 'Kezelt',

    testdrive_title: 'Tesztvezetés foglalása',
    testdrive_name: 'Név',
    testdrive_email: 'E-mail',
    testdrive_phone: 'Telefon',
    testdrive_date: 'Kívánt dátum',
    testdrive_time: 'Kívánt időpont',
    testdrive_message: 'Üzenet (opcionális)',
    testdrive_submit: 'Foglalás elküldése',
    testdrive_success: 'Köszönjük! Hamarosan felvesszük veled a kapcsolatot a tesztvezetés időpontjával kapcsolatban.',
    testdrive_error: 'Hiba történt. Próbáld meg később.',

    favorite_add: 'Kedvencekhez',
    favorite_remove: 'Eltávolítás',
    favorite_count: 'Kedvencek ({{n}})',
    compare_title: 'Autók összehasonlítása',
    compare_add: 'Összehasonlításhoz',
    compare_remove: 'Eltávolítás',
    compare_max: 'Maximum 3 autót lehet összehasonlítani.',
    compare_empty: 'Válassz autókat az összehasonlításhoz.',

    finance_title: 'Finanszírozási kalkulátor',
    finance_price: 'Autó ára (Ft)',
    finance_down: 'Önerő (Ft)',
    finance_months: 'Futamidő (hónap)',
    finance_rate: 'Kamatláb (%/év)',
    finance_monthly: 'Becsült havi törlesztő',
    finance_offer: 'Kérj személyre szabott ajánlatot',

    tradein_title: 'Csereautó értékbecslés',
    tradein_subtitle: 'Add meg a jelenlegi autód adatait, és kapsz egy becslést.',
    tradein_make: 'Márka',
    tradein_model: 'Modell',
    tradein_year: 'Év',
    tradein_mileage: 'Futott km',
    tradein_submit: 'Becslés kérése',
    tradein_success: 'Köszönjük! Hamarosan küldünk egy becslést.',
    tradein_placeholder_make: 'pl. Toyota',
    tradein_placeholder_model: 'pl. Corolla',

    trust_title: 'Miért minket válasszanak?',
    trust_sold: '{{n}}+ eladott autó',
    trust_years: '{{n}}+ év tapasztalat',
    trust_reviews: 'Ügyfélvélemények',
    trust_guarantee: 'Garanciális szerviz',

    notify_title: 'Értesíts, ha hasonló érkezik',
    notify_subtitle: 'Add meg az e-mail címed és a keresési feltételeket.',
    notify_email: 'E-mail',
    notify_submit: 'Feliratkozás',
    notify_success: 'Köszönjük! Értesítünk, ha megfelelő autó érkezik.',
    car_color: 'Szín',
    car_power: 'Teljesítmény',
    car_extras: 'Extrák',

    faq_title: 'Gyakran ismételt kérdések',
    faq_meta_title: 'GYIK | NovaDrive Motors',
    faq_q1: 'Milyen garanciát adtok az autókra?',
    faq_a1: 'Minden autónkra legalább 6 hónap garanciát adunk. A prémium kategóriás járművekre akár 12 hónap garancia is jár.',
    faq_q2: 'Lehetőség van finanszírozásra?',
    faq_a2: 'Igen, több bankkal együttműködve rugalmas hitel- és lízing konstrukciókat kínálunk. Használd a kalkulátorunkat a főoldalon, vagy kérj személyre szabott ajánlatot.',
    faq_q3: 'Fogadtok csereautót?',
    faq_a3: 'Természetesen. Kérj ingyenes értékbecslést a főoldalon a csereautó űrlapon keresztül. Hamarosan visszajelzünk.',
    faq_q4: 'Hogyan foglalhatok tesztvezetést?',
    faq_a4: 'Az autó adatlapján kattints a „Tesztvezetés foglalása” gombra, töltsd ki az űrlapot, és hamarosan felvesszük veled a kapcsolatot az időponttal kapcsolatban.',
    faq_q5: 'Hol található a showroomotok?',
    faq_a5: 'Budapesten, az Autó utca 1. szám alatt. Parkolási lehetőség az épület előtt. Előzetes egyeztetéssel hétvégén is fogadunk.',

    notfound_title: 'Az oldal nem található',
    notfound_message: 'A keresett oldal nem létezik vagy áthelyezésre került.',
    notfound_back: 'Vissza a főoldalra',

    cookie_title: 'Sütik használata',
    cookie_message: 'Weboldalunk sütiket használ a megfelelő működéshez és a felhasználói élmény javításához. A böngészéssel elfogadod a sütik használatát.',
    cookie_accept: 'Elfogadom',
    cookie_more: 'Részletek',

    skip_link: 'Ugrás a tartalomhoz',
    menu_open: 'Menü megnyitása',
    menu_close: 'Menü bezárása',

    callback_btn: 'Visszahívást kérek',
    callback_title: 'Visszahívást kérek',
    callback_subtitle: 'Hagyja meg adatait, és hamarosan felvesszük Önnel a kapcsolatot.',
    callback_name: 'Név',
    callback_phone: 'Telefonszám',
    callback_time: 'Kívánt időpont (opcionális)',
    callback_message: 'Üzenet (opcionális)',
    callback_submit: 'Kérés elküldése',
    callback_success: 'Köszönjük! Hamarosan felvesszük Önnel a kapcsolatot.',
    callback_error: 'Hiba történt. Próbálja meg később.',

    video_section_title: 'Bemutató videók',
    video_section_subtitle: 'Ismerje meg showroomunkat és kínálatunkat.',

    chat_btn: 'Chat',
    chat_title: 'Üzenet küldése',
    chat_placeholder: 'Írja be üzenetét...',
    chat_send: 'Küldés',
    chat_intro: 'Írjon nekünk, hamarosan válaszolunk!',
    chat_connecting: 'Csatlakozás...',

    admin_callbacks_title: 'Visszahívási kérelmek',
    admin_callbacks_count: '{{n}} kérés',
    admin_callbacks_mark: 'Kezelt',
    admin_chat_title: 'Élő chat',
    admin_chat_select: 'Válasszon beszélgetést',
    admin_chat_reply: 'Válasz írása...',
    admin_chat_send: 'Küldés',
  },
  en: {
    site_name: 'NovaDrive Motors',
    nav_inventory: 'Current offers',
    nav_about: 'About us',
    nav_faq: 'FAQ',
    nav_contact: 'Contact',
    nav_admin: 'Admin login',
    nav_admin_dashboard: 'Admin dashboard',
    footer: 'NovaDrive Motors · Demo car dealership · All content is for demonstration purposes only.',
    topbar_phone: 'Phone: +36 20 123 4567',
    topbar_email: 'Email: info@novadrive.hu',
    logo_subtitle: 'Premium Car Studio · Demo',
    meta_description: 'NovaDrive demo car dealership – modern, clean car catalog with current inventory, detailed listings, gallery and online contact form.',
    meta_og_desc: 'Clean, customer-friendly car catalog demo for dealerships.',

    hero_title: 'Our cars – premium selection',
    hero_lead: 'We welcome visitors with {{n}} vehicles. Browse our selection, filter by type, category or price, and get in touch with one click.',
    hero_cta: 'View catalog',
    hero_banner: '{{n}} vehicles in stock',

    inventory_title: 'Recently arrived',
    inventory_subtitle: 'Browse by type, category or price – filter and sort the results in real time.',
    inventory_count: '{{n}} items',
    inventory_loading: 'Loading offers...',
    inventory_error: 'Failed to load offers. Please refresh the page later.',
    inventory_empty: 'No cars match your filters. Adjust your search criteria or clear the filters.',
    inventory_aria: 'Available cars list',

    filter_title: 'Search',
    filter_make: 'Brand',
    filter_make_all: 'All brands',
    filter_category: 'Category',
    filter_category_all: 'All',
    filter_sort: 'Sort by',
    filter_sort_default: 'Default',
    filter_sort_price_asc: 'Price ascending',
    filter_sort_price_desc: 'Price descending',
    filter_sort_date_desc: 'Newest first',
    filter_sort_date_asc: 'Oldest first',
    filter_price_min: 'Price from (Ft)',
    filter_price_max: 'Price to (Ft)',
    filter_color: 'Color',
    filter_color_all: 'All colors',
    filter_power_min: 'Power (min) HP',
    filter_power_max: 'Power (max) HP',
    filter_search: 'Search',
    filter_search_count: 'Search ({{n}})',
    filter_clear: 'Clear filters',

    car_sold: 'Sold',
    car_featured: 'Featured',
    car_details: 'View details',
    car_back: 'Back to catalog',
    car_year: 'Year',
    car_mileage: 'Mileage (km)',
    car_fuel: 'Fuel type',
    car_transmission: 'Transmission',
    car_body: 'Body type',
    car_category: 'Category',
    car_offer: 'Request a custom offer or book a test drive.',
    car_loading: 'Loading car details...',
    car_error: 'Car not found or an error occurred while loading.',
    car_not_found: 'Car not found.',
    car_gallery_aria: 'Car image gallery',
    car_table_aria: 'Car details',
    car_image_alt: '{{0}} - image {{1}}',

    contact_title: 'Contact',
    contact_subtitle: 'Send us a message in just a few clicks – optionally select the car you are interested in.',
    contact_name: 'Name',
    contact_email: 'Email address',
    contact_phone: 'Phone (optional)',
    contact_car: 'Related car (optional)',
    contact_car_none: 'No specific car',
    contact_car_helper: 'Select which car you are writing about so we can help you faster.',
    contact_message: 'Message',
    contact_submit: 'Send message',
    contact_sending: 'Sending...',
    contact_error_required: 'Please fill in your name, email address and message.',
    contact_success: 'Thank you for your inquiry! We will get back to you soon.',
    contact_error_send: 'An error occurred while sending the message. Please try again later.',
    contact_hours_title: 'Opening hours',
    contact_hours_weekday: 'Monday–Friday: 9:00 AM–6:00 PM',
    contact_hours_saturday: 'Saturday: 9:00 AM–2:00 PM',
    contact_hours_sunday: 'Sunday: Closed',
    contact_social_title: 'Follow us',
    contact_address_title: 'Address',
    contact_address: '1234 Budapest, Auto Street 1.',

    about_title: 'About us',
    about_meta_title: 'About us | NovaDrive Motors',
    about_intro: 'NovaDrive Motors is more than a car dealership – we are a community where quality, honesty and customer focus come first in everything we do.',
    about_mission_title: 'Our mission',
    about_mission: 'We offer premium and reliable vehicles to our customers with transparent terms and personalized service. Every car we sell is thoroughly inspected so you can be sure: what you see is what you get.',
    about_values_title: 'Our values',
    about_value_quality_title: 'Quality',
    about_value_quality: 'We only offer carefully selected, inspected vehicles.',
    about_value_transparency_title: 'Transparency',
    about_value_transparency: 'No hidden costs – the price is the price, everything in one place.',
    about_value_service_title: 'Service',
    about_value_service: 'Personalized advice, financing options and trade-in estimates.',
    about_cta: 'Browse our inventory or get in touch with us.',

    admin_login_title: 'Admin login',
    admin_login_subtitle: 'Restricted area for the dealership. For the demo, use',
    admin_login_subtitle2: 'credentials.',
    admin_email: 'Email',
    admin_password: 'Password',
    admin_demo: 'Demo: admin@example.com / admin',
    admin_submit: 'Login',
    admin_submitting: 'Logging in...',
    admin_error_connection: 'Connection failed. Start the backend: cd backend && uvicorn app.main:app --port 8000',
    admin_error_credentials: 'Invalid credentials. Use: admin@example.com / admin',

    admin_dash_title: 'Admin dashboard',
    admin_dash_subtitle: 'Manage cars for sale and contact messages in one place.',
    admin_logout: 'Log out',

    admin_cars_title: 'Inventory management',
    admin_cars_count: '{{n}} cars in system',
    admin_cars_add: 'Add new car',
    admin_cars_loading: 'Loading cars...',
    admin_cars_error: 'Failed to load cars.',
    admin_cars_col_car: 'Car',
    admin_cars_col_price: 'Price (HUF)',
    admin_cars_col_category: 'Category',
    admin_cars_col_status: 'Status',
    admin_cars_col_actions: 'Actions',
    admin_cars_edit: 'Edit',
    admin_cars_sold: 'Mark as sold',
    admin_cars_reactivate: 'Reactivate',
    admin_cars_delete: 'Delete',
    admin_cars_status_sold: 'Sold',
    admin_cars_status_active: 'Active',
    admin_cars_modal_edit: 'Edit car details',
    admin_cars_modal_add: 'Add new car',
    admin_cars_label_title: 'Title',
    admin_cars_label_make: 'Brand',
    admin_cars_label_model: 'Model',
    admin_cars_label_year: 'Year',
    admin_cars_label_mileage: 'Mileage (km)',
    admin_cars_label_fuel: 'Fuel type',
    admin_cars_label_transmission: 'Transmission',
    admin_cars_label_body: 'Body type',
    admin_cars_label_category: 'Category',
    admin_cars_label_images: 'Upload images',
    admin_cars_upload_text: 'Click or drag images here (multiple files)',
    admin_cars_uploading: 'Uploading...',
    admin_cars_main_image: 'Main image',
    admin_cars_label_urls: 'Or image URLs (comma-separated)',
    admin_cars_label_description: 'Description',
    admin_cars_label_extras: 'Extras (comma-separated)',
    admin_cars_cancel: 'Cancel',
    admin_cars_save: 'Save',
    admin_cars_saving: 'Saving...',
    admin_cars_confirm_delete: 'Are you sure you want to delete:',

    admin_messages_title: 'Inbox',
    admin_messages_count: '{{n}} messages total',
    admin_messages_loading: 'Loading messages...',
    admin_messages_error: 'Failed to load messages.',
    admin_messages_col_sender: 'Sender',
    admin_messages_col_message: 'Message',
    admin_messages_col_car: 'Related car',
    admin_messages_col_status: 'Status',
    admin_messages_col_action: 'Action',
    admin_messages_mark_handled: 'Mark as handled',
    admin_messages_status_new: 'New',
    admin_messages_status_handled: 'Handled',

    testdrive_title: 'Book a test drive',
    testdrive_name: 'Name',
    testdrive_email: 'Email',
    testdrive_phone: 'Phone',
    testdrive_date: 'Preferred date',
    testdrive_time: 'Preferred time',
    testdrive_message: 'Message (optional)',
    testdrive_submit: 'Submit booking',
    testdrive_success: 'Thank you! We will contact you soon about the test drive.',
    testdrive_error: 'An error occurred. Please try again later.',

    favorite_add: 'Add to favorites',
    favorite_remove: 'Remove',
    favorite_count: 'Favorites ({{n}})',
    compare_title: 'Compare cars',
    compare_add: 'Add to compare',
    compare_remove: 'Remove',
    compare_max: 'You can compare up to 3 cars.',
    compare_empty: 'Select cars to compare.',

    finance_title: 'Financing calculator',
    finance_price: 'Car price (Ft)',
    finance_down: 'Down payment (Ft)',
    finance_months: 'Term (months)',
    finance_rate: 'Interest rate (%/year)',
    finance_monthly: 'Estimated monthly payment',
    finance_offer: 'Request a custom offer',

    tradein_title: 'Trade-in value estimate',
    tradein_subtitle: 'Enter your current car details for an estimate.',
    tradein_make: 'Brand',
    tradein_model: 'Model',
    tradein_year: 'Year',
    tradein_mileage: 'Mileage (km)',
    tradein_submit: 'Request estimate',
    tradein_success: 'Thank you! We will send you an estimate soon.',
    tradein_placeholder_make: 'e.g. Toyota',
    tradein_placeholder_model: 'e.g. Corolla',

    trust_title: 'Why choose us?',
    trust_sold: '{{n}}+ cars sold',
    trust_years: '{{n}}+ years experience',
    trust_reviews: 'Customer reviews',
    trust_guarantee: 'Warranty service',

    notify_title: 'Notify me when similar arrives',
    notify_subtitle: 'Enter your email and search criteria.',
    notify_email: 'Email',
    notify_submit: 'Subscribe',
    notify_success: 'Thank you! We will notify you when a matching car arrives.',
    car_color: 'Color',
    car_power: 'Power',
    car_extras: 'Extras',

    faq_title: 'Frequently asked questions',
    faq_meta_title: 'FAQ | NovaDrive Motors',
    faq_q1: 'What warranty do you offer on cars?',
    faq_a1: 'We offer at least 6 months warranty on all our cars. Premium category vehicles may come with up to 12 months warranty.',
    faq_q2: 'Do you offer financing?',
    faq_a2: 'Yes, we work with several banks to offer flexible loan and leasing options. Use our calculator on the homepage or request a personalized quote.',
    faq_q3: 'Do you accept trade-ins?',
    faq_a3: 'Absolutely. Request a free valuation on the homepage via the trade-in form. We will get back to you shortly.',
    faq_q4: 'How can I book a test drive?',
    faq_a4: 'On the car detail page, click the "Book a test drive" button, fill out the form, and we will contact you shortly about scheduling.',
    faq_q5: 'Where is your showroom located?',
    faq_a5: 'In Budapest, at Auto Street 1. Parking available in front of the building. We also welcome visitors on weekends by prior arrangement.',

    notfound_title: 'Page not found',
    notfound_message: 'The page you are looking for does not exist or has been moved.',
    notfound_back: 'Back to homepage',

    cookie_title: 'Cookie usage',
    cookie_message: 'Our website uses cookies for proper functionality and to improve your experience. By browsing, you accept the use of cookies.',
    cookie_accept: 'Accept',
    cookie_more: 'Details',

    skip_link: 'Skip to main content',
    menu_open: 'Open menu',
    menu_close: 'Close menu',

    callback_btn: 'Request callback',
    callback_title: 'Request a callback',
    callback_subtitle: 'Leave your details and we will get back to you shortly.',
    callback_name: 'Name',
    callback_phone: 'Phone number',
    callback_time: 'Preferred time (optional)',
    callback_message: 'Message (optional)',
    callback_submit: 'Submit request',
    callback_success: 'Thank you! We will contact you shortly.',
    callback_error: 'An error occurred. Please try again later.',

    video_section_title: 'Demo videos',
    video_section_subtitle: 'Discover our showroom and inventory.',

    chat_btn: 'Chat',
    chat_title: 'Send a message',
    chat_placeholder: 'Type your message...',
    chat_send: 'Send',
    chat_intro: 'Write to us, we will reply soon!',
    chat_connecting: 'Connecting...',

    admin_callbacks_title: 'Callback requests',
    admin_callbacks_count: '{{n}} requests',
    admin_callbacks_mark: 'Handled',
    admin_chat_title: 'Live chat',
    admin_chat_select: 'Select a conversation',
    admin_chat_reply: 'Type your reply...',
    admin_chat_send: 'Send',
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

function interpolate(str: string, args: (string | number)[]): string {
  let result = str;
  args.forEach((arg, i) => {
    result = result.replace(new RegExp(`\\{\\{${i}\\}\\}`, 'g'), String(arg));
  });
  if (args[0] != null) {
    result = result.replace(/\{\{n\}\}/g, String(args[0]));
  }
  return result;
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem(STORAGE_KEY);
    return (stored === 'en' || stored === 'hu') ? stored : 'hu';
  });

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = lang;
  }, [lang]);

  const setLang = (l: Lang) => setLangState(l);

  const t = (key: string, ...args: (string | number)[]): string => {
    const raw = translations[lang]?.[key] ?? translations.hu[key] ?? key;
    return args.length > 0 ? interpolate(raw, args) : raw;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
